services:
  - type: web
    name: hypemode-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: hypemode-mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: hypemode-mysql
          property: port
      - key: DB_USER
        fromDatabase:
          name: hypemode-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: hypemode-mysql
          property: password
      - key: DB_NAME
        fromDatabase:
          name: hypemode-mysql
          property: database
      - key: FRONTEND_URL
        value: https://hypemode-ecommerce-finalproject-fe.vercel.app

databases:
  - name: hypemode-mysql
    plan: free
    databaseName: hypemode_ecommerce
    user: hypemode_user

